#~/.dein.toml

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'junegunn/vim-easy-align'
[[plugins]]
repo = 'mattn/emmet-vim'

